# Generated by Django 3.0.4 on 2020-04-21 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0002_auto_20200409_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painter',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='painter_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painter',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
