# Generated by Django 3.0.4 on 2020-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0006_auto_20200421_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='genres',
            field=models.ManyToManyField(blank=True, to='NeuralPainter.Genre'),
        ),
    ]
