# Generated by Django 3.0.4 on 2020-04-24 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0008_auto_20200423_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='painter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paints', to='NeuralPainter.Painter'),
        ),
    ]
