# Generated by Django 3.0.4 on 2020-05-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0011_auto_20200516_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paints', to='NeuralPainter.Genre'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='painters', to='NeuralPainter.Genre'),
        ),
        migrations.AlterField(
            model_name='stylizedphoto',
            name='stylized_photo',
            field=models.ImageField(default='/static/img/no_image.jpg', null=True, upload_to='stylized_photo'),
        ),
    ]
