# Generated by Django 3.0.4 on 2020-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0012_auto_20200522_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylizedphoto',
            name='stylized_photo',
            field=models.ImageField(default='/media/stylized_photo/no_image.jpg', null=True, upload_to='stylized_photo'),
        ),
    ]
