# Generated by Django 3.0.4 on 2020-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralPainter', '0015_auto_20200522_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylizedphoto',
            name='stylized_photo',
            field=models.ImageField(null=True, upload_to='stylized_photo'),
        ),
    ]
